#!url=https://raw.githubusercontent.com/chazikai24/shadowrocket-rules/main/Modules/zt.module
#!name=佐糖
#!desc=佐糖双版本解锁会员
#!author=chazikai24

[Script]
佐糖=type=http-response,pattern=^https:\/\/awvp\.aoscdn\.com\/base\/vip\/client\/authorizations,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/zt.js
佐糖=type=http-response,pattern=^https:\/\/awvp\.aoscdn\.com\/base\/vip\/v2\/vips,requires-body=1,script-path=https://raw.githubusercontent.com/89996462/Quantumult-X/main/ycdz/zt.js

[MITM] 
hostname = %APPEND% awvp.aoscdn.com
